spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123123
        type: com.alibaba.druid.pool.DruidDataSource

#mybatis:
# 扫描classpath中mapper目录下的映射配置文件，针对映射文件放到了resources目录下
#    mapper-location: classpath:/mapper/*.xml
#定义包别名，使用pojo时可以直接使用pojo的类型，不用加包名
#    type-aliases-package: com.bjsxt.pojo